'use strict';
const scenes = [
 [24,'StarHeart','A little light. A cosmic connection.','Wonder',10,'Gentle interaction','starheart'],
 [26,'ImpossibleGarden','Waterfalls, wonder and a world that responds.','Nature',10,'Seated exploration','garden'],
 [20,'SleepingOcean','Discover a quiet world beneath the waves.','Nature',10,'Underwater encounters','ocean'],
 [21,'LumiStarfall','Catch a moment among the falling stars.','Wonder',10,'Gentle interaction','lumistarfall'],
 [22,'DreamRoad','Take the scenic route through a dream.','Journey',13,'Driving · moving viewpoint','dreamroad'],
 [23,'CloudVoyage','Let your imagination take flight.','Journey',13,'Flight · moving viewpoint','cloudvoyage'],
 [25,'FastLumiValley','Step into a luminous valley.','Nature',10,'Explore at your own pace','valley'],
 [30,'LumiValley','A little time in a brighter place.','Nature',10,'Explore at your own pace','valley'],
 [31,'spaceIsland','An island beneath a sky of possibilities.','Wonder',13,'Explore a space setting','space'],
 [27,'ImpossibleGarden_NoVideos','The garden, without its cinema sequences.','Nature',10,'No in-world videos','garden'],
 [28,'ImpossibleGarden_Mochi','Meet Mochi in an impossible garden.','Nature',10,'Mochi companion','garden'],
 [29,'ImpossibleGarden_Mochi_NoVideos','Mochi’s garden, without cinema sequences.','Nature',10,'Mochi · no in-world videos','garden'],
 [1,'Scene_1_Car_dealership','Explore the car showroom.','Explore',13,'Legacy scene · review suitability','showroom'],
 [2,'Scene_2_Castle','Discover a castle world.','Explore',13,'Legacy scene · review suitability','castle'],
 [3,'Scene_R1','Explore the original R1 environment.','Explore',13,'Legacy scene · review suitability','r1'],
 [4,'Scene_3_farm','Spend a moment on the farm.','Nature',13,'Legacy scene · review suitability','farm']
].map(([id,name,description,category,age,motion,art])=>({id,name,description,category,age,motion,art,title:({Scene_1_Car_dealership:'Car Dealership',Scene_2_Castle:'Castle',Scene_R1:'R1',Scene_3_farm:'Farm',ImpossibleGarden_NoVideos:'Impossible Garden · Pure',ImpossibleGarden_Mochi:'Impossible Garden · Mochi',ImpossibleGarden_Mochi_NoVideos:'Impossible Garden · Mochi Pure',spaceIsland:'Space Island'})[name]||name.replace(/([a-z])([A-Z])/g,'$1 $2')}));
const included=new Set(['starheart','dreamroad','cloudvoyage','lumistarfall']);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let launchUncertain=false;
let galleryPage=0;
let page='browse',selected=scenes[0],filter='All worlds',age='all',query='',config=null,catalog=[],heads=[],session=null,busy=false,timer=null,started=0,uploadUrls=new Map(),db;
function poster(s){if(window.KIOSK_RECORDINGS?.[s.name])return window.KIOSK_RECORDINGS[s.name].poster;return included.has(s.art)?`assets/${s.art}.jpg`:s.art==='garden'?'assets/garden.png':s.art==='ocean'?'assets/ocean.png':'assets/welcome.png'}
function videoSource(s){return uploadUrls.get(s.id)||window.KIOSK_RECORDINGS?.[s.name]?.video||(included.has(s.art)?`assets/${s.art}.mp4`:'')}
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',5000)}
function connection(){ $('connection').textContent=config?'○ Remote configured':'○ Preview mode' }
function navigate(next){if(busy&&!['session','complete'].includes(next)){toast('Please wait for the current action to finish.');return}if(session&&next!=='session'){toast('End the current experience before leaving.');return}document.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.load()});page=next;render();window.scrollTo(0,0)}
function render(){
 const root=$('app');root.querySelectorAll('video').forEach(v=>v.pause());
 if(page==='home'){root.innerHTML=`<section class="attract"><p class="eyebrow">A LITTLE WONDER. A MOMENT FOR YOU.</p><h1>IMMERSIVE SMILE</h1><p class="sub">Your World. Your Moment.</p><div class="welcome-bottom"><button id="enter" class="primary">TOUCH TO ENTER &nbsp; →</button><p>Discover immersive worlds designed around comfort, curiosity and connection.</p></div></section>`;$('enter').onclick=()=>navigate('browse');return}
 if(page==='browse'){
 root.innerHTML=`<section class="discovery content"><div class="discovery-intro"><div><p class="eyebrow">A MOMENT OF WONDER</p><h1>Where will you<br><em>escape today?</em></h1><p>Choose a world. Make it your moment.</p></div><div class="journey-step"><span class="step active">1</span><span>Choose a world</span><span class="step">2</span><span>Step inside</span></div></div><div class="browse-tools"><div class="filters" id="filters">${[['All worlds','All worlds'],['Nature','Nature & calm'],['Wonder','A little magic'],['Journey','An adventure']].map(([f,label])=>`<button class="${f===filter?'selected':''}" data-filter="${f}" aria-pressed="${f===filter}">${label}</button>`).join('')}</div><button id="ageHelp" class="text-button">Age guidance ⓘ</button></div><div class="section-label"><span id="count"></span><span>TAP A WORLD TO TAKE A LOOK</span></div><div class="grid" id="cards"></div><nav class="gallery-nav" aria-label="Browse worlds"><button id="previous">← Back</button><div id="pageCount" aria-live="polite"></div><button id="next">More worlds →</button></nav><p class="small-note gallery-note">Your pace. Your choice. Preview any world before you begin.</p></section>`;
 cards();$('filters').onclick=e=>{if(e.target.dataset.filter){filter=e.target.dataset.filter;galleryPage=0;render()}};$('ageHelp').onclick=()=>$('ageInfo').showModal();return;
 }
 if(page==='detail'){
 const family=familyFor(selected), warning=window.KIOSK_RECORDINGS?.[selected.name]?.reviewNote;
 root.innerHTML=`<section class="preview-page content"><div class="preview-nav"><button class="back" id="back">← All worlds</button><span class="eyebrow">TAKE A LOOK AROUND</span><button id="nextWorld" class="back">Next world →</button></div><div class="preview-stage">${media(selected)}<div class="preview-caption"><span class="tag">${selected.category}</span><h1>${esc(familyTitle(selected))}</h1><p>${familyDescription(selected)}</p></div></div><div class="preview-under"><div class="tags"><span class="tag">Suggested ${selected.age}+</span><span class="tag">${selected.motion.replace('Legacy scene · review suitability','Explore at your own pace')}</span></div><div class="media-controls"><button id="playPreview">Ⅱ Pause preview</button><button id="audioToggle">♫ Sound off</button></div></div>${family.length>1?`<div class="versions"><span>Choose your version</span><div>${family.map(v=>`<button data-version="${v.id}" class="${v.id===selected.id?'selected':''}" aria-pressed="${v.id===selected.id}">${versionLabel(v)}</button>`).join('')}</div><select id="versionSelect" class="version-select" aria-label="World version">${family.map(v=>`<option value="${v.id}" ${v.id===selected.id?'selected':''}>${versionLabel(v)}</option>`).join('')}</select></div>`:''}${warning?`<p class="review-notice">${selected.id===31?'This world is still being prepared. Choose another world to begin.':'This world needs a staff check before use.'}<button class="text-button" id="reviewDetails">Details</button></p>`:''}<div class="start-dock"><div><p class="eyebrow">${config?'READY WHEN YOU ARE':'TRY IT HERE'}</p><p>${config?'Put on your headset. We’ll take you there.':'Enjoy a preview on this screen.'}</p></div><button class="primary" id="start" ${selected.id===31?'disabled':''}>${selected.id===31?'COMING SOON':config?'LET’S BEGIN':'START PREVIEW'} <span>→</span></button></div><p class="recording-note">Recorded Unity preview · simulated interaction${config?' · Not a live headset view.':' · No headset connected.'}</p></section>`;
 $('back').onclick=()=>navigate('browse');$('nextWorld').onclick=()=>{if(busy)return;const list=galleryScenes();let i=list.findIndex(x=>familyFor(x).some(v=>v.id===selected.id));selected=list[(i+1)%list.length]||scenes[0];navigate('detail')};
 $('playPreview').disabled=!videoSource(selected);$('playPreview').onclick=()=>{const v=document.querySelector('video');if(!v)return;if(v.paused)playVideo();else v.pause()};bindAudio();$('start').onclick=start;
 document.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>{if(busy)return;selected=scenes.find(x=>x.id===Number(b.dataset.version));navigate('detail')});if($('versionSelect'))$('versionSelect').onchange=e=>{if(busy)return;selected=scenes.find(s=>s.id===Number(e.target.value));navigate('detail')};if($('reviewDetails'))$('reviewDetails').onclick=()=>toast(warning);
 const v=document.querySelector('video');if(v){v.onplay=()=>{$('playPreview').textContent='Ⅱ Pause preview'};v.onpause=()=>{if($('playPreview'))$('playPreview').textContent='▷ Play preview'};if(!matchMedia('(prefers-reduced-motion: reduce)').matches)playVideo();else $('playPreview').textContent='▷ Play preview'}return;
 }
 if(page==='session'){root.innerHTML=`<section class="content"><div class="session-title"><p class="eyebrow">${session.demo?'KIOSK PREVIEW':'YOUR EXPERIENCE'}</p><h1>${esc(selected.title)}</h1><p>Your touch brings worlds to life.</p></div><div class="session-grid">${media(selected)}<aside class="interaction"><p class="eyebrow">YOUR INTERACTION</p><div class="orb"></div><p>Squeeze the stress ball, or use your VR controller trigger.</p><div class="down">↓</div><h3>A world that responds</h3><p>Light, movement and atmosphere unfold inside the headset.</p></aside></div><p class="small-note" style="text-align:center">PRERECORDED PREVIEW · This is not a live headset view. Simulated interaction. Your headset experience may differ.</p><div class="media-controls"><button id="playPreview">▷ Play preview</button><button id="pausePreview">Ⅱ Pause preview only</button><button id="audioToggle">♫ Enable preview sound</button></div><div class="status-list"><div class="status-row"><span>Experience</span><strong id="experienceStatus">${session.demo?'Local preview only':'Command sent · awaiting headset'}</strong></div><div class="status-row"><span>Headset</span><strong id="headsetStatus">${session.demo?'Not connected':'Checking…'}</strong></div><div class="status-row"><span>Elapsed</span><strong id="elapsed">00:00</strong></div></div><div class="actions"><button id="end" class="primary">End experience</button></div></section>`;$('end').onclick=()=>{$('stopDescription').textContent=session.demo?'End this local kiosk preview.':'End this session and request the headset return to its lobby.';$('stopDialog').showModal()};$('playPreview').onclick=playVideo;bindAudio();$('pausePreview').onclick=()=>document.querySelector('video')?.pause();$('playPreview').disabled=$('pausePreview').disabled=!videoSource(selected);playVideo();return}
 if(page==='complete'){root.innerHTML=`<section class="attract"><p class="eyebrow">TAKE THAT LITTLE LIGHT WITH YOU</p><h1>A moment,<br>just for you.</h1><p class="sub">Your experience has ended.</p><div class="welcome-bottom"><button id="again" class="primary">EXPLORE MORE WORLDS →</button><p>Whenever you’re ready, another world awaits.</p></div></section>`;$('again').onclick=()=>navigate('browse')}
}
function familyFor(s){const ids=[26,27,28,29].includes(s.id)?[27,26,29,28]:[25,30].includes(s.id)?[25,30]:[s.id];return ids.map(id=>scenes.find(x=>x.id===id))}
function familyTitle(s){return [26,27,28,29].includes(s.id)?'Impossible Garden':[25,30].includes(s.id)?'Lumi Valley':s.title}
function familyDescription(s){return [26,27,28,29].includes(s.id)?'Waterfalls, wonder and a world that responds.':s.description}
function versionLabel(s){return ({26:'With cinema',27:'Garden only',28:'Mochi + cinema',29:'With Mochi',25:'Fast Lumi Valley',30:'Original valley'})[s.id]||s.title}
function galleryScenes(){return [25,20,27,24,21,22,23,1,2,3,4,31].map(id=>scenes.find(s=>s.id===id)).filter(s=>filter==='All worlds'||s.category===filter)}
function cards(){
 const list=galleryScenes(),pages=Math.max(1,Math.ceil(list.length/4));galleryPage=Math.min(galleryPage,pages-1);const visible=list.slice(galleryPage*4,galleryPage*4+4);
 $('count').textContent=`${list.length} WORLDS TO DISCOVER`;
 $('cards').innerHTML=visible.map(s=>`<button class="card" data-id="${s.id}" aria-label="Preview ${esc(familyTitle(s))}"><img loading="eager" src="${poster(s)}" alt=""><span class="card-top"><span>${s.id===31?'COMING SOON':s.category}</span><span>${s.age}+</span></span><span class="card-copy"><h3>${familyTitle(s)}</h3><span class="description">${familyDescription(s)}</span><span class="card-bottom"><span>${s.id===31?'See work in progress':'Explore this world'}</span><span class="arrow">↗</span></span></span></button>`).join('');
 $('pageCount').innerHTML=`<span class="page-dots">${Array.from({length:pages},(_,i)=>`<i class="${i===galleryPage?'active':''}"></i>`).join('')}</span><span>${galleryPage+1} of ${pages}</span>`;
 $('previous').disabled=galleryPage===0;$('next').disabled=galleryPage===pages-1;
 const turnPage=delta=>{galleryPage+=delta;cards();if(innerWidth<701)$('cards').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};$('previous').onclick=()=>turnPage(-1);$('next').onclick=()=>turnPage(1);
 $('cards').onclick=e=>{const c=e.target.closest('[data-id]');if(c&&!busy){selected=scenes.find(s=>s.id===Number(c.dataset.id));navigate('detail')}};
}
function media(s){let src=videoSource(s);return `<div class="hero">${src?`<video src="${esc(src)}" poster="${poster(s)}" loop muted playsinline preload="none" aria-label="Prerecorded ${esc(s.title)} preview"></video>`:`<img src="${poster(s)}" alt="${['garden','ocean'].includes(s.art)?'Scene screenshot':'Illustrative cover artwork'}"><div class="no-video">Recording not added yet. Staff can add this scene’s MP4 in setup.</div>`}<span class="badge">${src?(window.KIOSK_RECORDINGS?.[s.name]&&!uploadUrls.has(s.id)?'▷ UNITY RECORDING · SIMULATED INPUT':'▷ RECORDED PREVIEW'):'STILL PREVIEW'}</span></div>`}
function bindAudio(){const b=$('audioToggle');if(!b)return;b.disabled=!videoSource(selected);b.onclick=()=>{const v=document.querySelector('video');if(!v)return;v.muted=!v.muted;b.textContent=v.muted?'♫ Sound off':'♫ Sound on';if(!v.muted)playVideo()}}
function playVideo(){const v=document.querySelector('video');if(v)v.play().catch(()=>toast('Tap Play preview to start playback.'))}
async function api(path,options={}){let response=await fetch(config.url+path,{...options,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`Service returned ${response.status}. Check access and connection.`);return response.json()}
async function start(){if(launchUncertain){toast('A prior launch is unconfirmed. Check and end it in the staff portal before reloading this kiosk.');return}if(busy||session)return;busy=true;$('start').disabled=true;try{if(config){if(!config.headset)throw Error('Select an online headset in Staff setup.');if(!/^[0-9a-f-]{36}$/i.test(config.patient))throw Error('Enter a valid patient UUID in Staff setup.');const scenario=catalog.find(s=>s.scene_index===selected.id&&s.unity_scene_name===selected.name&&s.is_active!==false);if(!scenario)throw Error('This exact Unity scene is not in the active backend catalogue.');launchUncertain=true;let launched=await api('/scenario-sessions',{method:'POST',body:JSON.stringify({patient_id:config.patient,scenario_id:scenario.id,headset_id:config.headset})});launchUncertain=false;session={...launched,demo:false};}else session={demo:true};started=Date.now();navigate('session');timer=setInterval(tick,1000);if(!session.demo){if(!session.pushed_to_headset)$('experienceStatus').textContent='Session created · command not delivered';await pollHeadset()}}catch(e){toast(e.message+' If a launch timed out, check the staff portal before retrying.');if($('start')){$('start').disabled=launchUncertain;if(launchUncertain)$('start').textContent='LAUNCH UNCONFIRMED · CHECK STAFF PORTAL'}}finally{busy=false}}
let polling=false;
async function pollHeadset(){if(polling||!session||session.demo||!config)return;polling=true;try{heads=await api('/scenarios/headsets');if(page!=='session')return;const h=heads.find(h=>h.id===config.headset);$('headsetStatus').textContent=h?.online?'Online':'Offline / unavailable';$('experienceStatus').textContent=h?.online&&h.current_scene_index===selected.id?'Headset reports selected scene':session.pushed_to_headset?'Awaiting selected scene':'Command delivery unconfirmed'}catch(e){if($('headsetStatus'))$('headsetStatus').textContent='Connection stale · check headset'}finally{polling=false}}
function tick(){if(!session)return;const sec=Math.floor((Date.now()-started)/1000);if($('elapsed'))$('elapsed').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec%5===0)pollHeadset()}
$('confirmStop').onclick=async()=>{if(busy||!session)return;busy=true;$('confirmStop').disabled=true;try{if(!session.demo)await api(`/scenario-sessions/${encodeURIComponent(session.id)}/end`,{method:'POST',body:JSON.stringify({status:'completed'})});clearInterval(timer);session=null;$('stopDialog').close();navigate('complete')}catch(e){toast('Could not confirm session end. Check the headset and retry.')}finally{busy=false;$('confirmStop').disabled=false}};
$('setupForm').onsubmit=async e=>{e.preventDefault();if(session||busy){$('setupMessage').textContent='End the active experience before changing connection.';return}const old=config;try{let url=new URL($('api').value);if(url.protocol!=='https:'&&!(['localhost','127.0.0.1'].includes(url.hostname)&&url.protocol==='http:'))throw Error('Use HTTPS, or localhost for development.');if(url.username||url.password||url.search||url.hash)throw Error('Use a plain API URL.');config={url:url.href.replace(/\/$/,''),token:$('token').value.trim(),patient:$('patient').value.trim(),headset:''};[catalog,heads]=await Promise.all([api('/scenarios'),api('/scenarios/headsets')]);$('headset').innerHTML='<option value="">Choose a headset</option>'+heads.filter(h=>h.online).map(h=>`<option value="${esc(h.id)}">${esc(h.name||h.id)}</option>`).join('');$('setupMessage').textContent=`Connected. ${heads.filter(h=>h.online).length} online headsets. Select one below.`;connection()}catch(e){config=old;$('setupMessage').textContent=e.message}};
$('headset').onchange=e=>{if(config&&!session&&!busy){config.headset=e.target.value;connection();if(page==='detail')render()}};
$('disconnect').onclick=()=>{if(session||busy){toast('End the experience first.');return}config=null;catalog=[];heads=[];$('token').value='';$('patient').value='';$('headset').innerHTML='<option>Connect first</option>';connection();$('settings').close();render()};
$('recordScene').innerHTML=scenes.map(s=>`<option value="${s.id}">${s.title}</option>`).join('');
const request=indexedDB.open('immersive-smile-kiosk',1);request.onupgradeneeded=()=>request.result.createObjectStore('recordings');request.onsuccess=()=>{db=request.result;const cursor=db.transaction('recordings').objectStore('recordings').openCursor();cursor.onsuccess=()=>{let c=cursor.result;if(c){uploadUrls.set(c.key,URL.createObjectURL(c.value));c.continue()}else if(page==='browse')cards()}};
$('recordFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!db){$('recordMessage').textContent='Browser storage is unavailable.';return}if(file.size>200*1024*1024){$('recordMessage').textContent='Use a recording smaller than 200 MB.';return}const id=Number($('recordScene').value);const test=document.createElement('video');test.preload='metadata';const url=URL.createObjectURL(file);test.src=url;test.onloadedmetadata=()=>{const tx=db.transaction('recordings','readwrite');tx.objectStore('recordings').put(file,id);tx.oncomplete=()=>{if(uploadUrls.has(id))URL.revokeObjectURL(uploadUrls.get(id));uploadUrls.set(id,url);$('recordMessage').textContent='Recording saved on this kiosk.';if(page==='detail'||page==='browse')render()};tx.onerror=()=>{URL.revokeObjectURL(url);$('recordMessage').textContent='Storage is full or unavailable.'}};test.onerror=()=>{URL.revokeObjectURL(url);$('recordMessage').textContent='This browser cannot play that recording. Use H.264 MP4.'}};
$('home').onclick=()=>navigate('browse');$('setup').onclick=$('connection').onclick=()=>$('settings').showModal();$('fullscreen').onclick=()=>{(document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()).catch(()=>toast('Fullscreen is unavailable in this browser.'))};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
window.addEventListener('beforeunload',e=>{if(session&&!session.demo){e.preventDefault();e.returnValue=''}});let lastTouch=Date.now();['pointerdown','keydown'].forEach(type=>document.addEventListener(type,()=>lastTouch=Date.now()));setInterval(()=>{if(!session&&!document.querySelector('dialog[open]')&&Date.now()-lastTouch>180000&&(page!=='browse'||galleryPage!==0||filter!=='All worlds')){galleryPage=0;filter='All worlds';navigate('browse')}},10000);render();
