'use strict';
const scenes = [
 [24,'StarHeart','A little light. A cosmic connection.','Wonder',10,'Gentle interaction','starheart'],
 [26,'ImpossibleGarden','Waterfalls, wonder and a world that responds.','Nature',10,'Seated exploration','garden'],
 [20,'SleepingOcean','Discover a quiet world beneath the waves.','Nature',10,'Underwater encounters','ocean'],
 [21,'LumiStarfall','Catch a moment among the falling stars.','Wonder',10,'Gentle interaction','lumistarfall'],
 [22,'DreamRoad','Take the scenic route through a dream.','Journey',13,'Driving · moving viewpoint','dreamroad'],
 [23,'CloudVoyage','Let your imagination take flight.','Journey',13,'Flight · moving viewpoint','cloudvoyage'],
 [25,'FastLumiValley','Step into a luminous valley.','Nature',10,'Explore at your own pace','valley'],
 [30,'LumiValley','A little time in a brighter place.','Nature',10,'Explore at your own pace','valley'],
 [31,'spaceIsland','An island beneath a sky of possibilities.','Wonder',13,'Explore a space setting','space'],
 [27,'ImpossibleGarden_NoVideos','The garden, without its cinema sequences.','Nature',10,'No in-world videos','garden'],
 [28,'ImpossibleGarden_Mochi','Meet Mochi in an impossible garden.','Nature',10,'Mochi companion','garden'],
 [29,'ImpossibleGarden_Mochi_NoVideos','Mochi’s garden, without cinema sequences.','Nature',10,'Mochi · no in-world videos','garden'],
 [1,'Scene_1_Car_dealership','Explore the car showroom.','Explore',13,'Legacy scene · review suitability','showroom'],
 [2,'Scene_2_Castle','Discover a castle world.','Explore',13,'Legacy scene · review suitability','castle'],
 [3,'Scene_R1','Explore the original R1 environment.','Explore',13,'Legacy scene · review suitability','r1'],
 [4,'Scene_3_farm','Spend a moment on the farm.','Nature',13,'Legacy scene · review suitability','farm']
].map(([id,name,description,category,age,motion,art])=>({id,name,description,category,age,motion,art,title:({Scene_1_Car_dealership:'Car Dealership',Scene_2_Castle:'Castle',Scene_R1:'R1',Scene_3_farm:'Farm',ImpossibleGarden_NoVideos:'Impossible Garden · Pure',ImpossibleGarden_Mochi:'Impossible Garden · Mochi',ImpossibleGarden_Mochi_NoVideos:'Impossible Garden · Mochi Pure',spaceIsland:'Space Island'})[name]||name.replace(/([a-z])([A-Z])/g,'$1 $2')}));
const included=new Set(['starheart','dreamroad','cloudvoyage','lumistarfall']);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let launchUncertain=false;
let page='home',selected=scenes[0],filter='All worlds',age='all',query='',config=null,catalog=[],heads=[],session=null,busy=false,timer=null,started=0,uploadUrls=new Map(),db;
function poster(s){if(window.KIOSK_RECORDINGS?.[s.name])return window.KIOSK_RECORDINGS[s.name].poster;return included.has(s.art)?`assets/${s.art}.jpg`:s.art==='garden'?'assets/garden.png':s.art==='ocean'?'assets/ocean.png':'assets/welcome.png'}
function videoSource(s){return uploadUrls.get(s.id)||window.KIOSK_RECORDINGS?.[s.name]?.video||(included.has(s.art)?`assets/${s.art}.mp4`:'')}
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',5000)}
function connection(){ $('connection').textContent=config?'○ Remote configured':'○ Preview mode' }
function navigate(next){if(session&&next!=='session'){toast('End the current experience before leaving.');return}document.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.load()});page=next;render();window.scrollTo(0,0)}
function render(){
 const root=$('app');
 if(page==='home'){root.innerHTML=`<section class="attract"><p class="eyebrow">A LITTLE WONDER. A MOMENT FOR YOU.</p><h1>IMMERSIVE SMILE</h1><p class="sub">Your World. Your Moment.</p><div class="welcome-bottom"><button id="enter" class="primary">TOUCH TO ENTER &nbsp; →</button><p>Discover immersive worlds designed around comfort, curiosity and connection.</p></div></section>`;$('enter').onclick=()=>navigate('browse');return}
 if(page==='browse'){root.innerHTML=`<section class="content"><div class="intro"><p class="eyebrow">CHOOSE YOUR MOMENT</p><h1>Where would you<br>like to go?</h1><p>A quiet escape. A little adventure. A world for you.</p></div><div class="filters" id="filters">${['All worlds','Nature','Wonder','Journey','Explore'].map(f=>`<button class="${f===filter?'selected':''}" data-filter="${f}">${f}</button>`).join('')}</div><div class="filters" id="ages">${[['all','Every audience'],['10','Ages 10–12'],['13','Teens 13–17'],['18','Adults 18+']].map(([v,l])=>`<button data-age="${v}" class="${v===age?'selected':''}">${l}</button>`).join('')}<button id="ageHelp" class="text-button">Age guidance ⓘ</button></div><input class="search" id="search" aria-label="Search worlds" placeholder="Find your world…" value="${esc(query)}"><div class="section-label"><span id="count"></span><span>TOUCH A WORLD TO EXPLORE</span></div><div class="grid" id="cards"></div><p class="small-note">Age groups are suggested content audiences. Adult supervision for ages 10–12. ${scenes.filter(s=>videoSource(s)).length} scene recordings available. Unity recordings use simulated stress-ball input and scripted adaptation.</p></section>`;cards();$('search').oninput=e=>{query=e.target.value;cards()};$('filters').onclick=e=>{if(e.target.dataset.filter){filter=e.target.dataset.filter;render()}};$('ages').onclick=e=>{if(e.target.dataset.age){age=e.target.dataset.age;render()}};$('ageHelp').onclick=()=>$('ageInfo').showModal();return}
 if(page==='detail'){root.innerHTML=`<section class="content"><button class="back" id="back">← All worlds</button>${media(selected)}<div class="media-controls"><button id="playPreview">▷ Play recorded preview</button><button id="audioToggle">♫ Enable preview sound</button></div><div class="details-heading"><p class="eyebrow">${selected.category.toUpperCase()} · WORLD ${selected.id}</p><h1>${esc(selected.title)}</h1><p>${selected.description}</p><div class="tags"><span class="tag">Suggested ${selected.age}+</span><span class="tag">${selected.motion}</span></div></div><div class="detail-body">${window.KIOSK_RECORDINGS?.[selected.name]?.reviewNote?`<p class="error">${esc(window.KIOSK_RECORDINGS[selected.name].reviewNote)}</p>`:""}<p>Your squeeze or controller trigger is your way to interact. The headset runs the experience; this screen plays a lightweight recording.</p><p class="small-note">Unity scene: ${selected.name}<br>${!window.KIOSK_RECORDINGS?.[selected.name]&&!included.has(selected.art)&&!['garden','ocean'].includes(selected.art)?'Illustrative cover art · not a screenshot of this scene.':''}</p></div><div class="start-panel"><p class="eyebrow">${config?'REMOTE EXPERIENCE':'KIOSK PREVIEW'}</p><h3>${config?'Put on the headset when you’re ready.':'Explore the kiosk experience.'}</h3><button class="primary" id="start">${config?'START EXPERIENCE':'TRY KIOSK PREVIEW'} &nbsp; →</button><p>${config?'A scene command will be sent to the selected headset.':'Preview mode does not control a headset.'}</p></div></section>`;$('back').onclick=()=>navigate('browse');$('playPreview').disabled=!videoSource(selected);$('playPreview').onclick=()=>playVideo();bindAudio();$('start').onclick=start;return}
 if(page==='session'){root.innerHTML=`<section class="content"><div class="session-title"><p class="eyebrow">${session.demo?'KIOSK PREVIEW':'YOUR EXPERIENCE'}</p><h1>${esc(selected.title)}</h1><p>Your touch brings worlds to life.</p></div><div class="session-grid">${media(selected)}<aside class="interaction"><p class="eyebrow">YOUR INTERACTION</p><div class="orb"></div><p>Squeeze the stress ball, or use your VR controller trigger.</p><div class="down">↓</div><h3>A world that responds</h3><p>Light, movement and atmosphere unfold inside the headset.</p></aside></div><p class="small-note" style="text-align:center">PRERECORDED PREVIEW · This is not a live headset view. Simulated input and adaptation; not live DQN inference. Interactions may differ.</p><div class="media-controls"><button id="playPreview">▷ Play preview</button><button id="pausePreview">Ⅱ Pause preview only</button><button id="audioToggle">♫ Enable preview sound</button></div><div class="status-list"><div class="status-row"><span>Experience</span><strong id="experienceStatus">${session.demo?'Local preview only':'Command sent · awaiting headset'}</strong></div><div class="status-row"><span>Headset</span><strong id="headsetStatus">${session.demo?'Not connected':'Checking…'}</strong></div><div class="status-row"><span>Stress ball / adaptation</span><strong>Check headset for current status</strong></div><div class="status-row"><span>Elapsed</span><strong id="elapsed">00:00</strong></div></div><p class="eyebrow">INTERACTION LEVEL</p><div class="meter"><div></div></div><p class="small-note">Live interaction telemetry is not displayed in this version.</p><div class="actions"><button id="end" class="primary">End experience</button></div></section>`;$('end').onclick=()=>{$('stopDescription').textContent=session.demo?'End this local kiosk preview.':'End this session and request the headset return to its lobby.';$('stopDialog').showModal()};$('playPreview').onclick=playVideo;bindAudio();$('pausePreview').onclick=()=>document.querySelector('video')?.pause();$('playPreview').disabled=$('pausePreview').disabled=!videoSource(selected);playVideo();return}
 if(page==='complete'){root.innerHTML=`<section class="attract"><p class="eyebrow">TAKE THAT LITTLE LIGHT WITH YOU</p><h1>A moment,<br>just for you.</h1><p class="sub">Your experience has ended.</p><div class="welcome-bottom"><button id="again" class="primary">EXPLORE MORE WORLDS →</button><p>Whenever you’re ready, another world awaits.</p></div></section>`;$('again').onclick=()=>navigate('browse')}
}
function cards(){const list=scenes.filter(s=>(filter==='All worlds'||s.category===filter)&&(age==='all'||s.age<=Number(age))&&`${s.title} ${s.name} ${s.description}`.toLowerCase().includes(query.toLowerCase()));$('count').textContent=`${list.length} WORLDS`;$('cards').innerHTML=list.length?list.map(s=>`<button class="card" data-id="${s.id}" aria-label="Explore ${esc(s.title)}"><img loading="lazy" src="${poster(s)}" alt=""><span class="card-copy"><span class="eyebrow">${s.category}</span><h3>${s.title}</h3><span class="description">${s.description}</span><span class="meta">${s.age}+ SUGGESTED · ${videoSource(s)?'VIDEO PREVIEW':'RECORDING NEEDED'}</span><span class="arrow">→</span></span></button>`).join(''):'<div class="empty">No worlds found. Try another filter.</div>';$('cards').onclick=e=>{let c=e.target.closest('[data-id]');if(c){selected=scenes.find(s=>s.id===Number(c.dataset.id));navigate('detail')}}}
function media(s){let src=videoSource(s);return `<div class="hero">${src?`<video src="${esc(src)}" poster="${poster(s)}" loop muted playsinline preload="none" aria-label="Prerecorded ${esc(s.title)} preview"></video>`:`<img src="${poster(s)}" alt="${['garden','ocean'].includes(s.art)?'Scene screenshot':'Illustrative cover artwork'}"><div class="no-video">Recording not added yet. Staff can add this scene’s MP4 in setup.</div>`}<span class="badge">${src?(window.KIOSK_RECORDINGS?.[s.name]&&!uploadUrls.has(s.id)?'▷ UNITY RECORDING · SIMULATED INPUT':'▷ RECORDED PREVIEW'):'STILL PREVIEW'}</span></div>`}
function bindAudio(){const b=$('audioToggle');if(!b)return;b.disabled=!videoSource(selected);b.onclick=()=>{const v=document.querySelector('video');if(!v)return;v.muted=!v.muted;b.textContent=v.muted?'♫ Enable preview sound':'♫ Mute preview sound';if(!v.muted)playVideo()}}
function playVideo(){const v=document.querySelector('video');if(v)v.play().catch(()=>toast('Tap Play preview to start playback.'))}
async function api(path,options={}){let response=await fetch(config.url+path,{...options,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`Service returned ${response.status}. Check access and connection.`);return response.json()}
async function start(){if(launchUncertain){toast('A prior launch is unconfirmed. Check and end it in the staff portal before reloading this kiosk.');return}if(busy||session)return;busy=true;$('start').disabled=true;try{if(config){if(!config.headset)throw Error('Select an online headset in Staff setup.');if(!/^[0-9a-f-]{36}$/i.test(config.patient))throw Error('Enter a valid patient UUID in Staff setup.');const scenario=catalog.find(s=>s.scene_index===selected.id&&s.unity_scene_name===selected.name&&s.is_active!==false);if(!scenario)throw Error('This exact Unity scene is not in the active backend catalogue.');launchUncertain=true;let launched=await api('/scenario-sessions',{method:'POST',body:JSON.stringify({patient_id:config.patient,scenario_id:scenario.id,headset_id:config.headset})});launchUncertain=false;session={...launched,demo:false};}else session={demo:true};started=Date.now();navigate('session');timer=setInterval(tick,1000);if(!session.demo){if(!session.pushed_to_headset)$('experienceStatus').textContent='Session created · command not delivered';await pollHeadset()}}catch(e){toast(e.message+' If a launch timed out, check the staff portal before retrying.');if($('start')){$('start').disabled=launchUncertain;if(launchUncertain)$('start').textContent='LAUNCH UNCONFIRMED · CHECK STAFF PORTAL'}}finally{busy=false}}
let polling=false;
async function pollHeadset(){if(polling||!session||session.demo||!config)return;polling=true;try{heads=await api('/scenarios/headsets');if(page!=='session')return;const h=heads.find(h=>h.id===config.headset);$('headsetStatus').textContent=h?.online?'Online':'Offline / unavailable';$('experienceStatus').textContent=h?.online&&h.current_scene_index===selected.id?'Headset reports selected scene':session.pushed_to_headset?'Awaiting selected scene':'Command delivery unconfirmed'}catch(e){if($('headsetStatus'))$('headsetStatus').textContent='Connection stale · check headset'}finally{polling=false}}
function tick(){if(!session)return;const sec=Math.floor((Date.now()-started)/1000);if($('elapsed'))$('elapsed').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec%5===0)pollHeadset()}
$('confirmStop').onclick=async()=>{if(busy||!session)return;busy=true;$('confirmStop').disabled=true;try{if(!session.demo)await api(`/scenario-sessions/${encodeURIComponent(session.id)}/end`,{method:'POST',body:JSON.stringify({status:'completed'})});clearInterval(timer);session=null;$('stopDialog').close();navigate('complete')}catch(e){toast('Could not confirm session end. Check the headset and retry.')}finally{busy=false;$('confirmStop').disabled=false}};
$('setupForm').onsubmit=async e=>{e.preventDefault();if(session){$('setupMessage').textContent='End the active experience before changing connection.';return}const old=config;try{let url=new URL($('api').value);if(url.protocol!=='https:'&&!(['localhost','127.0.0.1'].includes(url.hostname)&&url.protocol==='http:'))throw Error('Use HTTPS, or localhost for development.');if(url.username||url.password||url.search||url.hash)throw Error('Use a plain API URL.');config={url:url.href.replace(/\/$/,''),token:$('token').value.trim(),patient:$('patient').value.trim(),headset:''};[catalog,heads]=await Promise.all([api('/scenarios'),api('/scenarios/headsets')]);$('headset').innerHTML='<option value="">Choose a headset</option>'+heads.filter(h=>h.online).map(h=>`<option value="${esc(h.id)}">${esc(h.name||h.id)}</option>`).join('');$('setupMessage').textContent=`Connected. ${heads.filter(h=>h.online).length} online headsets. Select one below.`;connection()}catch(e){config=old;$('setupMessage').textContent=e.message}};
$('headset').onchange=e=>{if(config&&!session){config.headset=e.target.value;connection();if(page==='detail')render()}};
$('disconnect').onclick=()=>{if(session){toast('End the experience first.');return}config=null;catalog=[];heads=[];$('token').value='';$('patient').value='';$('headset').innerHTML='<option>Connect first</option>';connection();$('settings').close();render()};
$('recordScene').innerHTML=scenes.map(s=>`<option value="${s.id}">${s.title}</option>`).join('');
const request=indexedDB.open('immersive-smile-kiosk',1);request.onupgradeneeded=()=>request.result.createObjectStore('recordings');request.onsuccess=()=>{db=request.result;const cursor=db.transaction('recordings').objectStore('recordings').openCursor();cursor.onsuccess=()=>{let c=cursor.result;if(c){uploadUrls.set(c.key,URL.createObjectURL(c.value));c.continue()}else if(page==='browse')cards()}};
$('recordFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!db){$('recordMessage').textContent='Browser storage is unavailable.';return}if(file.size>200*1024*1024){$('recordMessage').textContent='Use a recording smaller than 200 MB.';return}const id=Number($('recordScene').value);const test=document.createElement('video');test.preload='metadata';const url=URL.createObjectURL(file);test.src=url;test.onloadedmetadata=()=>{const tx=db.transaction('recordings','readwrite');tx.objectStore('recordings').put(file,id);tx.oncomplete=()=>{if(uploadUrls.has(id))URL.revokeObjectURL(uploadUrls.get(id));uploadUrls.set(id,url);$('recordMessage').textContent='Recording saved on this kiosk.';if(page==='detail'||page==='browse')render()};tx.onerror=()=>{URL.revokeObjectURL(url);$('recordMessage').textContent='Storage is full or unavailable.'}};test.onerror=()=>{URL.revokeObjectURL(url);$('recordMessage').textContent='This browser cannot play that recording. Use H.264 MP4.'}};
$('home').onclick=()=>navigate('home');$('setup').onclick=$('connection').onclick=()=>$('settings').showModal();$('fullscreen').onclick=()=>{(document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()).catch(()=>toast('Fullscreen is unavailable in this browser.'))};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
window.addEventListener('beforeunload',e=>{if(session&&!session.demo){e.preventDefault();e.returnValue=''}});let lastTouch=Date.now();['pointerdown','keydown'].forEach(type=>document.addEventListener(type,()=>lastTouch=Date.now()));setInterval(()=>{if(!session&&!document.querySelector('dialog[open]')&&Date.now()-lastTouch>180000&&page!=='home')navigate('home')},10000);render();
